spring:
  application:
    name: api-gateway-service
  config:
    import: optional:configserver:http://localhost:9876
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://user-service
          predicates:
            - Path=/users/**
#          filters:
#            - name: CustomHeader

        - id: jobService
          uri: lb://job-service
          predicates:
            - Path=/jobs/**
#          filters:
#            - name: CustomHeader

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8080



